### ISSUE TITLE
.md/ formatting support for RESPOND type messages

### ISSUE THREAD

**Issue by aka13-404** [nlef/moonraker-telegram-bot#202]
### What would you like to see added?

It would be cool to have more complex formatting availble for status messages. 
@xyzroe Would be nice if you could post your ideas in this ticket.

**Comment by xyzroe** [comment]
At the moment when we call tgalarm or tgnotify we can only pass a text string.
It would be great if we could use Emoji, text formatting (markdown or html) and line breaks.
Looking at the example described in the wiki, this will allow when the insert filament macro is called instead of two messages, send one and make it shorter or more noticeable through the use of emoji.
Of course I would like to use it on all notifications, with photos and status.

**Comment by xyzroe** [comment]
While I was trying to send messages in different ways, I found that Klipper swears "Malformed command" there is a * symbol in the command, which in MD means bold.
I don't know if this can be bypassed, but if so, there is html formatting as a last resort.

**Comment by nlef** [comment]
supported tags are in [telegram docs](https://core.telegram.org/bots/api#formatting-options). User must escape characters by himself. 
@xyzroe you are welcome)

**Comment by xyzroe** [comment]
👍 Thanks. I'l try later and give a feedback.
