### ISSUE TITLE
Remove Menu from Telegram Bot if you change the Bot

### ISSUE THREAD

**Issue by Bloodpack** [nlef/moonraker-telegram-bot#257]
### What would you like to see added?

Is there an option to remove the menu button and the commands from the telegram bot if you want to change the bot?

i have changed the bot and still have the menu on my old telegram bot
![Anmerkung 2023-02-25 102845](https://user-images.githubusercontent.com/26135135/221349850-7c2237fe-bc31-4ab4-8060-8d79a5b19978.png)

**Comment by aka13-404** [comment]
Telegram stores which commands are available on its side.
Whatever it is you are running instead, does not write anything, so the old configuration is used.
 If you want, you can try and expand our uninstaller, so that it sends an empty command list to telegram, if for whatever reason you reuse tokens/bots for different purposes. 
This is not a value-adding feature, so we will not work on it from our side.
