### ISSUE TITLE
Individual status messages

### ISSUE THREAD

**Issue by cross-x7** [nlef/moonraker-telegram-bot#265]
### What would you like to see added?

Can it be made that status-messages during printing don't "override" themselves but instead a new message for each update is sent?
When I check my printers during printing, I would like to scroll through the images made during the print, alongside with other informations about heater, time, etc for each image. Not only would it be kinda cool to see the individual images without having to create a timelapse, but it also helps with troubleshooting when a print fails. 
With individual messages you could browse the "history" of the print, to see when the print failed and maybe also figure out why it failed

**Comment by aka13-404** [comment]
We had this bahaviour some time ago on much older versions.
You can either roll back to those versions, if the features they offer are sufficient for you, or reimplement that behaviour with the recent changes to the structure/internal workings of the bot.

We are not really that interested in that feature (since we did not bother to reimplement it, as you understand) and will not implement it. 

if you are not capable of reimplementing that feature yourself and are willing to donate a reasonable amount (such a feature will be 5+ hours development and testing time), we can implement it ourselves. Feel free to contact me in that case.
